### ISSUE TITLE
Errors while running.

### ISSUE THREAD

**Issue by kttn** [mrrfv/open-android-backup#118]
## Device info

Manufacturer: **Samsung**
Android version: **13**
Custom ROM/rooted? - **No**
Model: **Galaxy Note 20**

## System info

Available disk space: **320gb**
Operating system: **Ubuntu 22.04**

---

**Describe the issue below.**

Everything was going great, and then I got these messages and after them, I got kicked out -- everything was going well before this and I didn't really have any problem with the setup, which I had completed and the program was just doing its thing. I went without hooks, if that's pertinent. 

I'm unsure if the backup is complete, just short a few things, or if it's just corrupted now. There is 9gb in the **backup-tmp** folder.
```

> Exporting contacts (as vCard), call logs as well as SMS messages (as CSV).
> 0.00 B 0:00:00 [0.00 B/s] [<=>                                                 ]
> tar: This does not look like a tar archive
> tar: Exiting with failure status due to previous errors
> Errors occurred while backing up . - this file (or multiple files) might've been ignored.
> mv: cannot stat './backup-tmp/open-android-backup-temp/open-android-backup-contact*.vcf': No such file or directory
> No contacts found on device - ignoring.
> mv: cannot stat './backup-tmp/open-android-backup-temp/SMS_Messages.csv': No such file or directory
```

Fully admit this could be user error, but I really have no idea what's going wrong!

All help appreciated!

Nick

**Comment by mrrfv** [comment]
Try using the `adb` exporting method (the script asks you for it at the beginning). Maybe your phone doesn't support the default one.

**Comment by kttn** [comment]
> Try using the `adb` exporting method (the script asks you for it at the beginning). Maybe your phone doesn't support the default one.

Hey yeah, I ended up doing that and it worked. Thanks so much for your time!
