### ISSUE TITLE
Runtime error: Function a/e not defined.

### ISSUE THREAD

**Issue by Nudin** [mrrfv/open-android-backup#59]
## System info
Available disk space: plenty
Operating system: Arch Linux

---

**Describe the issue below.**

When I use open-android-backup my output is littered with "runtime error" messages:

```
...
? What do you want to do? (Use arrow keys)
Runtime error (func=(main), adr=6): Function a not defined.
Runtime error (func=(main), adr=3): Function e not defined.
Runtime error (func=(main), adr=6): Function a not defined.
Runtime error (func=(main), adr=3): Function e not defined.
❯ Backup
  Restore
Runtime error (func=(main), adr=6): Function a not defined.
Runtime error (func=(main)Backup
Open Android Backup will install a companion app on your device, which will allow for contacts and other data to be backed up and restored.
...
```

**Comment by mrrfv** [comment]
This appears to be a problem with Inquirer.sh, which is one of the dependencies of this project. It's been known for causing trouble in the past. I'll see if a migration to [options.select](https://github.com/hinell/options-select-bash) or similar project is possible.

What terminal emulator and shell are you using? Could you try a different terminal app and plain old bash?

**Comment by mrrfv** [comment]
Fixed by removing Inquirer.sh - this should fix the problem. Let me know if the issue persists.
