### ISSUE TITLE
nothing happens when run the script

### ISSUE THREAD

**Issue by eboelens** [mrrfv/open-android-backup#74]
## Device info

Manufacturer: Zenfone 8
Android version: 12
Custom ROM/rooted? yes=/e/ 1.14     not rooted
Model:Sake

## System info

Available disk space: 210Gb available
Operating system: /e/ 1.14 

---

**Describe the issue below.
command backup.sh and nothing happens

erik@+++:~/Documents/Open Android Backup$ ls
backup.sh            extras            open-android-backup-companion.apk
backup-windows.ps1   functions         README.md
_config.yml          hooks.example.sh  windows-dependencies
convenience-scripts  LICENSE
erik@+++:~/Documents/Open Android Backup$ .backup.sh
erik@+++:~/Documents/Open Android Backup$

**Comment by eboelens** [comment]
running backup.sh from linux explorer = it works :+1:

**Comment by mrrfv** [comment]
Try `./backup.sh` instead of `.backup.sh`.

**Comment by mrrfv** [comment]
I'm going to close this now as it appears to be fixed, please leave a comment if you'd like to reopen.
