### ISSUE TITLE
Feature request: check for required apps before starting a backup

### ISSUE THREAD

**Issue by byron-hawkins** [mrrfv/open-android-backup#80]
## not device or system related

---

**Describe the issue below.**

When backup.sh begins a backup with required apps missing on the destination platform, it unleashes a massive stream of errors that are not particularly intuitive. For example, when `pv` is missing, `tar` subsequently complains that the file does not appear to be a tar (because actually there is no such file, since there was no `pv` to complete that step). 

Would it be possible to check for the presence of required apps before the backup starts, and simply tell the user that app `X` must be installed first? In my case, I did run the specified `dnf` command, but for some reason it didn't actually do the installations until I deliberately installed them one at a time, each with a separate `dnf` command.

**Comment by mrrfv** [comment]
Fixed, thanks for the suggestion!
