### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by VenimK** [mrrfv/open-android-backup#84]
When using this on windows,

i have to install a distro' with wsl
When running the script, and have to choose a backup map, it allways says, 
Can t''t find the map ?????

**Comment by mrrfv** [comment]
Please provide more information about the problem so I can help you better.

> Can t''t find the map ?????

Do you mean the backup location? It must be a directory that already exists.

**Comment by VenimK** [comment]
I got it working now with wsl Ubuntu installed

ThX

**Comment by mrrfv** [comment]
Good to hear, closing this now.

P.S. It's generally a good idea to let others know what steps did you take in order to fix the problem, in case someone else has the same issue.

**Comment by VenimK** [comment]
i think it was a problem with the WSL Kali ...
