### ISSUE TITLE
Erase not optional.

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [mrrfv/open-android-backup#95]
From the README (emphasis mine):

> **Optionally** securely erases all unencrypted temporary files created by the script.

When I ran the script, no option to skip or quit-script was presented at this, or any other, stage. This is not optional. Docs are incorrect.

**Comment by mrrfv** [comment]
You're misunderstanding the meaning of "secure erase" used in this sentence. It simply means that the temporary data will be removed in a way that's near impossible to recover (by overwriting it with random data and/or zeros at least once).

The script offers 3 data erase modes:
- Fast, which just removes the files with rm, and is generally considered insecure
- Slow and Extra Slow that overwrite the data before actually removing it, also known as secure erase.

If you need access to the script's unencrypted temporary data, you can use the `discouraged_disable_archive` environment variable for that. See the [Automation/Unattended Backups](https://github.com/mrrfv/open-android-backup#automationunattended-backups) section of the docs for more information.

**Comment by ParaplegicRacehorse** [comment]
So... This deletes a temporary cache _created by OAB_ and not the original files? Is it, then, safe to interrupt the process if my intention in creating a backup was to restore to a new device and wipe the original device? Or, is there some logic which will  prevent me from 'restoring' to a different device?

**Comment by mrrfv** [comment]
> This deletes a temporary cache created by OAB and not the original files?

Correct, the final (encrypted & compressed) backup files as well as data that wasn't created by OAB are never removed without your consent (the `backup-tmp` folder counts as a temporary cache).

> Is it, then, safe to interrupt the process if my intention in creating a backup was to restore to a new device and wipe the original device? 

Interrupt what process, to be exact? It's recommended that you don't prematurely end the script, as you may have a hard time restoring the data afterwards (the script's restore functionality expects a `.7z` archive created by OAB).

> Or, is there some logic which will prevent me from 'restoring' to a different device?

There's nothing preventing you from restoring your data to another device, although architectural compatibility issues with apps may occur under certain rare circumstances (such issues have never been reported, but I know they're possible).
