### ISSUE TITLE
Where backups are saving?

### ISSUE THREAD

**Issue by Erz3** [mrrfv/open-android-backup#96]
I need the location where backup was save locally, becuse I want sync it with other app to a cloud storage service. Is it possible?

Thanks in advance.

**Comment by mrrfv** [comment]
Backups are saved as `.7z` archives in the destination directory specified at the beginning of the backup process. The default backup location (if you haven't changed it) is the directory you've been in at the time of the backup. Syncing the backups to cloud storage or another remote server is doable.

**Comment by Erz3** [comment]
@mrrfv I can't specify a directory. Running the app I just see two options, export and import backup.

**Comment by mrrfv** [comment]
Don't run the app manually/separately, use the script and follow its instructions.

**Comment by Erz3** [comment]
I see… Well, I just was looking for an app to backup a few encrypted files without need stay connected to my PC. In any case, Thanks you.
